# ---------------------------------------------------------------------------- #
#                                Default profile                               #
# ---------------------------------------------------------------------------- #

# --------------------------------- Compiler --------------------------------- #

[profile.default]
solc_version = '0.8.13'
optimizer = true
optimizer_runs = 5000
libs = ["node_modules", "lib"]
out = 'artifacts'
test = 'test'
src = 'src'
gas_reports = ['*']
invariant = { fail_on_revert = true }
fs_permissions = [{ access = "read", path = "./artifacts"}]


# ---------------------------------- Format ---------------------------------- #

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"

# ---------------------------------------------------------------------------- #
#                                 Local profile                                #
# ---------------------------------------------------------------------------- #

[profile.local]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.local.fuzz]
[profile.local.invariant]
runs = 1
depth = 15
# call_override = true # makes invariant tests hang
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                             Heavy fuzzing profile                            #
# ---------------------------------------------------------------------------- #

[profile.heavy_fuzzing]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_fuzzing.fuzz]
runs = 1_000_000

[profile.heavy_fuzzing.invariant]
runs = 1_000_000
depth = 30
# call_override = true
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                                  CI profile                                  #
# ---------------------------------------------------------------------------- #

[profile.ci]
verbosity = 4

# ---------------------------------- Fuzzing --------------------------------- #

[profile.ci.fuzz]
runs = 256

[profile.ci.invariant]
runs = 256
depth = 5
# call_override = false
dictionary_weight = 40
optimizer_runs = 999999
out = 'artifacts'
test = 'test'
src = 'src'
libs = ['node_modules', 'lib']
bytecode_hash = "none"
gas_reports = ['*']

fs_permissions = [{ access = "read", path = "./artifacts" }]
